USE [Carrefour_Atacadao]
GO

/****** Object:  Table [dbo].[TB_CLIENTE]    Script Date: 15/05/2023 10:18:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TB_CLIENTE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](150) NULL,
	[RG] [varchar](20) NULL,
	[CPF] [varchar](20) NULL,
	[DATA_NASCIMENTO] [date] NULL,
	[TELEFONE] [varchar](20) NULL,
	[EMAIL] [varchar](150) NULL,
	[COD_EMPRESA] [int] NOT NULL,
 CONSTRAINT [PK_TB_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

